using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_AUDIO_OUTPUT_STATE
    //{
        // PARTY_AUDIO_OUTPUT_STATE_NO_OUTPUT = 0,
        // PARTY_AUDIO_OUTPUT_STATE_INITIALIZED = 1,
        // PARTY_AUDIO_OUTPUT_STATE_NOT_FOUND = 2,
        // PARTY_AUDIO_OUTPUT_STATE_UNSUPPORTED_FORMAT = 3,
        // PARTY_AUDIO_OUTPUT_STATE_ALREADY_IN_USE = 4,
        // PARTY_AUDIO_OUTPUT_STATE_UNKNOWN_ERROR = 5,
    //}
    //PARTY_AUDIO_OUTPUT_STATE;
    public enum PARTY_AUDIO_OUTPUT_STATE : UInt32
    {
        PARTY_AUDIO_OUTPUT_STATE_NO_OUTPUT = 0,
        PARTY_AUDIO_OUTPUT_STATE_INITIALIZED = 1,
        PARTY_AUDIO_OUTPUT_STATE_NOT_FOUND = 2,
        PARTY_AUDIO_OUTPUT_STATE_UNSUPPORTED_FORMAT = 3,
        PARTY_AUDIO_OUTPUT_STATE_ALREADY_IN_USE = 4,
        PARTY_AUDIO_OUTPUT_STATE_UNKNOWN_ERROR = 5,
    }
}