using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_AUDIO_DEVICE_SELECTION_TYPE
    //{
        // PARTY_AUDIO_DEVICE_SELECTION_TYPE_NONE = 0,
        // PARTY_AUDIO_DEVICE_SELECTION_TYPE_SYSTEM_DEFAULT = 1,
        // PARTY_AUDIO_DEVICE_SELECTION_TYPE_PLATFORM_USER_DEFAULT = 2,
        // PARTY_AUDIO_DEVICE_SELECTION_TYPE_MANUAL = 3,
    //} PARTY_AUDIO_DEVICE_SELECTION_TYPE;
    public enum PARTY_AUDIO_DEVICE_SELECTION_TYPE : UInt32
    {
        PARTY_AUDIO_DEVICE_SELECTION_TYPE_NONE = 0,
        PARTY_AUDIO_DEVICE_SELECTION_TYPE_SYSTEM_DEFAULT = 1,
        PARTY_AUDIO_DEVICE_SELECTION_TYPE_PLATFORM_USER_DEFAULT = 2,
        PARTY_AUDIO_DEVICE_SELECTION_TYPE_MANUAL = 3,
    }
}