using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR
    //{
        // PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_SILENT = 0,
        // PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_TALKING = 1,
        // PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_AUDIO_INPUT_MUTED = 2,
        // PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_NO_AUDIO_INPUT = 3,
    //} PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR;
    public enum PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR : UInt32
    {
        PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_SILENT = 0,
        PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_TALKING = 1,
        PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_AUDIO_INPUT_MUTED = 2,
        PARTY_LOCAL_CHAT_CONTROL_CHAT_INDICATOR_NO_AUDIO_INPUT = 3,
    }
}