using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_CHAT_PERMISSION_OPTIONS
    //{
    //    PARTY_CHAT_PERMISSION_OPTIONS_NONE = 0x0000,
    //    PARTY_CHAT_PERMISSION_OPTIONS_SEND_MICROPHONE_AUDIO = 0x0001,
    //    PARTY_CHAT_PERMISSION_OPTIONS_SEND_TEXT_TO_SPEECH_AUDIO = 0x0002,
    //    PARTY_CHAT_PERMISSION_OPTIONS_SEND_AUDIO = 0x0003,
    //    PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_MICROPHONE_AUDIO = 0x0004,
    //    PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_TEXT_TO_SPEECH_AUDIO = 0x0008,
    //    PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_AUDIO = 0x000c,
    //    PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_TEXT = 0x0010,
    //}
    //PARTY_CHAT_PERMISSION_OPTIONS;
    public enum PARTY_CHAT_PERMISSION_OPTIONS : UInt32
    {
        PARTY_CHAT_PERMISSION_OPTIONS_NONE = 0x0000,
        PARTY_CHAT_PERMISSION_OPTIONS_SEND_MICROPHONE_AUDIO = 0x0001,
        PARTY_CHAT_PERMISSION_OPTIONS_SEND_TEXT_TO_SPEECH_AUDIO = 0x0002,
        PARTY_CHAT_PERMISSION_OPTIONS_SEND_AUDIO = 0x0003,
        PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_MICROPHONE_AUDIO = 0x0004,
        PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_TEXT_TO_SPEECH_AUDIO = 0x0008,
        PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_AUDIO = 0x000c,
        PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_TEXT = 0x0010,
    }
}