using System;

namespace PartyXBLCSharpSDK
{
    //typedef enum PARTY_XBL_STATE_CHANGE_TYPE
    //{
    //    PARTY_XBL_STATE_CHANGE_TYPE_CREATE_LOCAL_CHAT_USER_COMPLETED,
    //    PARTY_XBL_STATE_CHANGE_TYPE_LOCAL_CHAT_USER_DESTROYED,
    //    PARTY_XBL_STATE_CHANGE_TYPE_REQUIRED_CHAT_PERMISSION_INFO_CHANGED,
    //    PARTY_XBL_STATE_CHANGE_TYPE_TOKEN_AND_SIGNATURE_REQUESTED,
    //    PARTY_XBL_STATE_CHANGE_TYPE_LOGIN_TO_PLAYFAB_COMPLETED,
    //    PARTY_XBL_STATE_CHANGE_TYPE_GET_ENTITY_IDS_FROM_XBOX_LIVE_USER_IDS_COMPLETED,
    //}
    //PARTY_XBL_STATE_CHANGE_TYPE;
    public enum PARTY_XBL_STATE_CHANGE_TYPE : UInt32
    {
        PARTY_XBL_STATE_CHANGE_TYPE_CREATE_LOCAL_CHAT_USER_COMPLETED,
        PARTY_XBL_STATE_CHANGE_TYPE_LOCAL_CHAT_USER_DESTROYED,
        PARTY_XBL_STATE_CHANGE_TYPE_REQUIRED_CHAT_PERMISSION_INFO_CHANGED,
        PARTY_XBL_STATE_CHANGE_TYPE_TOKEN_AND_SIGNATURE_REQUESTED,
        PARTY_XBL_STATE_CHANGE_TYPE_LOGIN_TO_PLAYFAB_COMPLETED,
        PARTY_XBL_STATE_CHANGE_TYPE_GET_ENTITY_IDS_FROM_XBOX_LIVE_USER_IDS_COMPLETED,
    }
}