using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_CHAT_CONTROL_CHAT_INDICATOR
    //{
        // PARTY_CHAT_CONTROL_CHAT_INDICATOR_SILENT = 0,
        // PARTY_CHAT_CONTROL_CHAT_INDICATOR_TALKING = 1,
        // PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_VOICE_DISABLED = 2,
        // PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_COMMUNICATIONS_MUTED = 3,
    //} PARTY_CHAT_CONTROL_CHAT_INDICATOR;
    public enum PARTY_CHAT_CONTROL_CHAT_INDICATOR : UInt32
    {
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_SILENT = 0,
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_TALKING = 1,
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_VOICE_DISABLED = 2,
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_COMMUNICATIONS_MUTED = 3,
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_NO_REMOTE_INPUT = 4,
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_REMOTE_AUDIO_INPUT_MUTED = 5,
    }
}