using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_CHAT_CONTROL_CHAT_INDICATOR
    //{
    //    PARTY_CHAT_CONTROL_CHAT_INDICATOR_SILENT,
    //    PARTY_CHAT_CONTROL_CHAT_INDICATOR_TALKING,
    //    PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_VOICE_DISABLED,
    //    PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_COMMUNICATIONS_MUTED,
    //} PARTY_CHAT_CONTROL_CHAT_INDICATOR;
    public enum PARTY_CHAT_CONTROL_CHAT_INDICATOR : UInt32
    {
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_SILENT = 0,
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_TALKING = 1,
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_VOICE_DISABLED = 2,
        PARTY_CHAT_CONTROL_CHAT_INDICATOR_INCOMING_COMMUNICATIONS_MUTED = 3,
    }
}