using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_SYNTHESIZE_TEXT_TO_SPEECH_TYPE
    //{
        // PARTY_SYNTHESIZE_TEXT_TO_SPEECH_TYPE_NARRATION = 0,
        // PARTY_SYNTHESIZE_TEXT_TO_SPEECH_TYPE_VOICE_CHAT = 1,
    //} PARTY_SYNTHESIZE_TEXT_TO_SPEECH_TYPE;
    public enum PARTY_SYNTHESIZE_TEXT_TO_SPEECH_TYPE : UInt32
    {
        PARTY_SYNTHESIZE_TEXT_TO_SPEECH_TYPE_NARRATION = 0,
        PARTY_SYNTHESIZE_TEXT_TO_SPEECH_TYPE_VOICE_CHAT = 1,
    }
}