// AUTO-GENERATED BY PreBuild.ps1 - DO NOT MODIFY
#if UNITY_STANDALONE || UNITY_IOS || UNITY_ANDROID || UNITY_GAMECORE || MICROSOFT_GAME_CORE
namespace PlayFab.Party
{
    internal static class Version
    {
        public static readonly string PartyNativeVersion = "{1.7.0}56101";
        public static readonly string PartyUnityVersion = "{1.7.0.0-main.0}56101";
    }
}
#endif
