using System;
using PartyXBLCSharpSDK.Interop;

namespace PartyXBLCSharpSDK
{
    //typedef enum PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING
    //{
    //    PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING_ALLOWED,
    //    PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING_FRIENDS_ONLY,
    //    PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING_DISALLOWED,
    //} PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING;
    public enum PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING : UInt32
    {
        PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING_ALLOWED = 0,
        PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING_FRIENDS_ONLY = 1,
        PARTY_XBL_CROSS_NETWORK_COMMUNICATION_PRIVACY_SETTING_DISALLOWED = 2,
    }
}