using System;
using PartyXBLCSharpSDK.Interop;

namespace PartyXBLCSharpSDK
{
    //typedef enum PARTY_XBL_CHAT_PERMISSION_MASK_REASON
    //{
    //    PARTY_XBL_CHAT_PERMISSION_MASK_REASON_NO_RESTRICTION,
    //    PARTY_XBL_CHAT_PERMISSION_MASK_REASON_DETERMINING,
    //    PARTY_XBL_CHAT_PERMISSION_MASK_REASON_PRIVILEGE,
    //    PARTY_XBL_CHAT_PERMISSION_MASK_REASON_PRIVACY,
    //    PARTY_XBL_CHAT_PERMISSION_MASK_REASON_INVALID_TARGET_USER,
    //    PARTY_XBL_CHAT_PERMISSION_MASK_REASON_XBOX_LIVE_SERVICE_ERROR,
    //    PARTY_XBL_CHAT_PERMISSION_MASK_REASON_UNKNOWN_ERROR,
    //} PARTY_XBL_CHAT_PERMISSION_MASK_REASON;
    public enum PARTY_XBL_CHAT_PERMISSION_MASK_REASON : UInt32
    {
        PARTY_XBL_CHAT_PERMISSION_MASK_REASON_NO_RESTRICTION = 0,
        PARTY_XBL_CHAT_PERMISSION_MASK_REASON_DETERMINING = 1,
        PARTY_XBL_CHAT_PERMISSION_MASK_REASON_PRIVILEGE = 2,
        PARTY_XBL_CHAT_PERMISSION_MASK_REASON_PRIVACY = 3,
        PARTY_XBL_CHAT_PERMISSION_MASK_REASON_INVALID_TARGET_USER = 4,
        PARTY_XBL_CHAT_PERMISSION_MASK_REASON_XBOX_LIVE_SERVICE_ERROR = 5,
        PARTY_XBL_CHAT_PERMISSION_MASK_REASON_UNKNOWN_ERROR = 6,
        PARTY_XBL_CHAT_PERMISSION_MASK_REASON_RESOLVE_USER_ISSUE = 7,
    }
}