using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_CHAT_TEXT_RECEIVED_OPTIONS
    //{
        // PARTY_CHAT_TEXT_RECEIVED_OPTIONS_NONE = 0x0000,
        // PARTY_CHAT_TEXT_RECEIVED_OPTIONS_FILTERED_OFFENSIVE_TERMS = 0x0001,
        // PARTY_CHAT_TEXT_RECEIVED_OPTIONS_FILTERED_ENTIRE_MESSAGE = 0x0002,
        // PARTY_CHAT_TEXT_RECEIVED_OPTIONS_FILTERED_DUE_TO_ERROR = 0x0004,
    //} PARTY_CHAT_TEXT_RECEIVED_OPTIONS;
    public enum PARTY_CHAT_TEXT_RECEIVED_OPTIONS : UInt32
    {
        PARTY_CHAT_TEXT_RECEIVED_OPTIONS_NONE = 0x0000,
        PARTY_CHAT_TEXT_RECEIVED_OPTIONS_FILTERED_OFFENSIVE_TERMS = 0x0001,
        PARTY_CHAT_TEXT_RECEIVED_OPTIONS_FILTERED_ENTIRE_MESSAGE = 0x0002,
        PARTY_CHAT_TEXT_RECEIVED_OPTIONS_FILTERED_DUE_TO_ERROR = 0x0004,
    }
}