using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS
    //{
    //    PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS_NONE = 0x0000,
    //    PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS_EXCLUDE_GAME_CORE_PREFERRED_UDP_MULTIPLAYER_PORT = 0x0001,
    //}
    //PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS;
    public enum PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS : UInt32
    {
        PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS_NONE = 0x0000,
        PARTY_LOCAL_UDP_SOCKET_BIND_ADDRESS_OPTIONS_EXCLUDE_GAME_CORE_PREFERRED_UDP_MULTIPLAYER_PORT = 0x0001,
    }
}