using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_DESTROYED_REASON
    //{
        // PARTY_DESTROYED_REASON_REQUESTED = 0,
        // PARTY_DESTROYED_REASON_DISCONNECTED = 1,
        // PARTY_DESTROYED_REASON_KICKED = 2,
        // PARTY_DESTROYED_REASON_DEVICE_LOST_AUTHENTICATION = 3,
        // PARTY_DESTROYED_REASON_CREATION_FAILED = 4,
    //}
    //PARTY_DESTROYED_REASON;
    public enum PARTY_DESTROYED_REASON : UInt32
    {
        PARTY_DESTROYED_REASON_REQUESTED = 0,
        PARTY_DESTROYED_REASON_DISCONNECTED = 1,
        PARTY_DESTROYED_REASON_KICKED = 2,
        PARTY_DESTROYED_REASON_DEVICE_LOST_AUTHENTICATION = 3,
        PARTY_DESTROYED_REASON_CREATION_FAILED = 4,
    }
}