// AUTO-GENERATED BY PreBuild.ps1 - DO NOT MODIFY
namespace PlayFab.Party
{
    public static class Version
    {
        public static readonly string PartyNativeVersion = "Default";
        public static readonly string PartyUnityVersion = "Default";
    }
}
