using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_AUDIO_INPUT_STATE
    //{
        // PARTY_AUDIO_INPUT_STATE_NO_INPUT = 0,
        // PARTY_AUDIO_INPUT_STATE_INITIALIZED = 1,
        // PARTY_AUDIO_INPUT_STATE_NOT_FOUND = 2,
        // PARTY_AUDIO_INPUT_STATE_USER_CONSENT_DENIED = 3,
        // PARTY_AUDIO_INPUT_STATE_UNSUPPORTED_FORMAT = 4,
        // PARTY_AUDIO_INPUT_STATE_ALREADY_IN_USE = 5,
        // PARTY_AUDIO_INPUT_STATE_UNKNOWN_ERROR = 6,
    //}
    //PARTY_AUDIO_INPUT_STATE;
    public enum PARTY_AUDIO_INPUT_STATE : UInt32
    {
        PARTY_AUDIO_INPUT_STATE_NO_INPUT = 0,
        PARTY_AUDIO_INPUT_STATE_INITIALIZED = 1,
        PARTY_AUDIO_INPUT_STATE_NOT_FOUND = 2,
        PARTY_AUDIO_INPUT_STATE_USER_CONSENT_DENIED = 3,
        PARTY_AUDIO_INPUT_STATE_UNSUPPORTED_FORMAT = 4,
        PARTY_AUDIO_INPUT_STATE_ALREADY_IN_USE = 5,
        PARTY_AUDIO_INPUT_STATE_UNKNOWN_ERROR = 6,
    }
}