using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_AUDIO_INPUT_STATE
    //{
    //    PARTY_AUDIO_INPUT_STATE_NO_INPUT,
    //    PARTY_AUDIO_INPUT_STATE_INITIALIZED,
    //    PARTY_AUDIO_INPUT_STATE_NOT_FOUND,
    //    PARTY_AUDIO_INPUT_STATE_USER_CONSENT_DENIED,
    //    PARTY_AUDIO_INPUT_STATE_UNSUPPORTED_FORMAT,
    //    PARTY_AUDIO_INPUT_STATE_ALREADY_IN_USE,
    //    PARTY_AUDIO_INPUT_STATE_UNKNOWN_ERROR,
    //}
    //PARTY_AUDIO_INPUT_STATE;
    public enum PARTY_AUDIO_INPUT_STATE : UInt32
    {
        PARTY_AUDIO_INPUT_STATE_NO_INPUT,
        PARTY_AUDIO_INPUT_STATE_INITIALIZED,
        PARTY_AUDIO_INPUT_STATE_NOT_FOUND,
        PARTY_AUDIO_INPUT_STATE_USER_CONSENT_DENIED,
        PARTY_AUDIO_INPUT_STATE_UNSUPPORTED_FORMAT,
        PARTY_AUDIO_INPUT_STATE_ALREADY_IN_USE,
        PARTY_AUDIO_INPUT_STATE_UNKNOWN_ERROR,
    }
}