using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_LOCAL_USER_REMOVED_REASON
    //{
        // PARTY_LOCAL_USER_REMOVED_REASON_AUTHENTICATION_FAILED = 0,
        // PARTY_LOCAL_USER_REMOVED_REASON_REMOVE_LOCAL_USER = 1,
        // PARTY_LOCAL_USER_REMOVED_REASON_DESTROY_LOCAL_USER = 2,
        // PARTY_LOCAL_USER_REMOVED_REASON_DESTROY_NETWORK = 3,
    //}
    //PARTY_LOCAL_USER_REMOVED_REASON;
    public enum PARTY_LOCAL_USER_REMOVED_REASON : UInt32
    {
        PARTY_LOCAL_USER_REMOVED_REASON_AUTHENTICATION_FAILED = 0,
        PARTY_LOCAL_USER_REMOVED_REASON_REMOVE_LOCAL_USER = 1,
        PARTY_LOCAL_USER_REMOVED_REASON_DESTROY_LOCAL_USER = 2,
        PARTY_LOCAL_USER_REMOVED_REASON_DESTROY_NETWORK = 3,
    }
}