using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_INVITATION_REVOCABILITY
    //{
        // PARTY_INVITATION_REVOCABILITY_CREATOR = 0,
        // PARTY_INVITATION_REVOCABILITY_ANYONE = 1,
    //} PARTY_INVITATION_REVOCABILITY;
    public enum PARTY_INVITATION_REVOCABILITY : UInt32
    {
        PARTY_INVITATION_REVOCABILITY_CREATOR = 0,
        PARTY_INVITATION_REVOCABILITY_ANYONE = 1,
    }
}