using System;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK
{
    //typedef enum PARTY_NETWORK_STATISTIC
    //{
        // PARTY_NETWORK_STATISTIC_AVERAGE_RELAY_SERVER_ROUND_TRIP_LATENCY_IN_MILLISECONDS = 0,
        // PARTY_NETWORK_STATISTIC_SENT_PROTOCOL_PACKETS = 1,
        // PARTY_NETWORK_STATISTIC_SENT_PROTOCOL_BYTES = 2,
        // PARTY_NETWORK_STATISTIC_RETRIED_PROTOCOL_PACKETS = 3,
        // PARTY_NETWORK_STATISTIC_RETRIED_PROTOCOL_BYTES = 4,
        // PARTY_NETWORK_STATISTIC_DROPPED_PROTOCOL_PACKETS = 5,
        // PARTY_NETWORK_STATISTIC_RECEIVED_PROTOCOL_PACKETS = 6,
        // PARTY_NETWORK_STATISTIC_RECEIVED_PROTOCOL_BYTES = 7,
        // PARTY_NETWORK_STATISTIC_CURRENTLY_QUEUED_SEND_MESSAGES = 8,
        // PARTY_NETWORK_STATISTIC_CURRENTLY_QUEUED_SEND_MESSAGE_BYTES = 9,
        // PARTY_NETWORK_STATISTIC_CURRENTLY_ACTIVE_SEND_MESSAGES = 10,
        // PARTY_NETWORK_STATISTIC_CURRENTLY_ACTIVE_SEND_MESSAGE_BYTES = 11,
        // PARTY_NETWORK_STATISTIC_TIMED_OUT_SEND_MESSAGES = 12,
        // PARTY_NETWORK_STATISTIC_TIMED_OUT_SEND_MESSAGE_BYTES = 13,
        // PARTY_NETWORK_STATISTIC_CANCELED_SEND_MESSAGES = 14,
        // PARTY_NETWORK_STATISTIC_CANCELED_SEND_MESSAGE_BYTES = 15,
    //} PARTY_NETWORK_STATISTIC;
    public enum PARTY_NETWORK_STATISTIC : UInt32
    {
        PARTY_NETWORK_STATISTIC_AVERAGE_RELAY_SERVER_ROUND_TRIP_LATENCY_IN_MILLISECONDS = 0,
        PARTY_NETWORK_STATISTIC_SENT_PROTOCOL_PACKETS = 1,
        PARTY_NETWORK_STATISTIC_SENT_PROTOCOL_BYTES = 2,
        PARTY_NETWORK_STATISTIC_RETRIED_PROTOCOL_PACKETS = 3,
        PARTY_NETWORK_STATISTIC_RETRIED_PROTOCOL_BYTES = 4,
        PARTY_NETWORK_STATISTIC_DROPPED_PROTOCOL_PACKETS = 5,
        PARTY_NETWORK_STATISTIC_RECEIVED_PROTOCOL_PACKETS = 6,
        PARTY_NETWORK_STATISTIC_RECEIVED_PROTOCOL_BYTES = 7,
        PARTY_NETWORK_STATISTIC_CURRENTLY_QUEUED_SEND_MESSAGES = 8,
        PARTY_NETWORK_STATISTIC_CURRENTLY_QUEUED_SEND_MESSAGE_BYTES = 9,
        PARTY_NETWORK_STATISTIC_CURRENTLY_ACTIVE_SEND_MESSAGES = 10,
        PARTY_NETWORK_STATISTIC_CURRENTLY_ACTIVE_SEND_MESSAGE_BYTES = 11,
        PARTY_NETWORK_STATISTIC_TIMED_OUT_SEND_MESSAGES = 12,
        PARTY_NETWORK_STATISTIC_TIMED_OUT_SEND_MESSAGE_BYTES = 13,
        PARTY_NETWORK_STATISTIC_CANCELED_SEND_MESSAGES = 14,
        PARTY_NETWORK_STATISTIC_CANCELED_SEND_MESSAGE_BYTES = 15,
    }
}